---
title: A Bíblia do R
author: Michelangelo R. dos Anjos
date: '2019-04-07'
slug: a-biblia-do-r
categories:
  - R
  - Turoriais
tags:
  - R
  - Code
  - Basic
  - Tutorial
editor_options: 
  chunk_output_type: console
output:
  blogdown::html_page:
    toc: true
---

<a name="abcd"> Esse </a> é o primeiro post e o que eu considero o principal e mais importante, pois a ideia de criação do site surgiu por causa de um backup de códigos que eu criei conforme as necessidades iam aparecendo e carregava ele comigo para todo lado para consultar quando precisava. Dessa forma, decidi organizá-lo melhor, upar na internet para facilitar o acesso e compartilhar com mais pessoas que tenham interesse e espero que possa ser útil para mais alguém como é muito importante para mim (já que minha memória não é das melhores :laughing:).

O post estará em constante atualização, pois sempre surge algo novo para aprendermos e a ideia é passar a linguagem R para frente sempre de maneira simples e didática, talvez a organização não fique a das melhores, mas vou procurar me esforçar ao máximo, caso o sumário não fique muito claro, recomendo utilizar o *"Ctrl F"* que sempre me salvou e pode ajudar vocês também.

Por último, antes de começar realmente os códigos, vocês encontraram meio misturado códigos *dplyr* com o *R raiz*, mas será em momentos na qual os códigos possuem a mesma função mas simplesmente podem ser escritos em estruturas diferentes. Acho muito importante saber as diversas maneiras de programar pois existem horas que uma será mais fácil que a outra. Por exemplo, na minha opinião, o *R raiz* é mais fácil para programar rotinas, loop, for, if, while, etc. Já o *dplyr* é mais fácil para acessar, consultar, agrupar, exibir resultados de uma tabela.

-------------------------------------------------------------------

[Volte ao topo](#abcd)